### ISSUE TITLE
Contouring issue

### ISSUE THREAD

**Issue by FranzThomsen1089** [meteoinfo/wContour_CSharp#1]
Hi

I am trying to use this library and seems to be having an issue in a specific case where I think the resulting polygons are not right. Before I start going into details, can I ask if you are actively maintaining this library?

Kind Regards
Franz

**Comment by Yaqiang** [comment]
Yes, I am maintaning this library.

**Comment by JustinCase1089** [comment]
Great, thanks, much appreciated. I have a grid of data and I am trying to create a shape file with a multipolygon corresponding to each contour. The shape file part I am using nettopologysuite for. I have built my application from the example application. There may be something I have misunderstood. In below I have loaded my grid data and list of x and y

```
            double[] contours = {12.5, 13};
            const double undefined = -1111;
            // I am not sure what s1 is, can you tell me or point in the direction of somewhere where I can find out?
            var s1 = new int[1, 1];
            var borders = Contour.TracingBorders(grid, x.ToArray(), y.ToArray(), ref s1, undefined);
            var contourLines = Contour.TracingContourLines(grid, x.ToArray(), y.ToArray(), contours.Length, contours, undefined, borders, s1);
            var contourPolygons = Contour.TracingPolygons(grid, contourLines, borders, contours);

            if (!Directory.Exists("Result"))
            {
                Directory.CreateDirectory("Result");
            }

            foreach (var group in contourPolygons.GroupBy(r => r.OutLine.Value))
            {
                // I here group by the value of the outline ... I believe this is the way I can see what belongs to each contour, is this correct?
                // I am of the impression that the first group here should include all polygons that have values TO 12.5, is this correct?
                int polygonNumber = 0;
                foreach (var polygon in group)
                {
                    // I then loop over all the polygons and for each ontline I create a linearring ... thats what nettopologysuite needs
                    var outline = _GetLinearRing(polygon.OutLine.PointList);
                    var value = group.Key;

                    var rings = new List<LinearRing>();
                    if (polygon.HasHoles)
                    {
                        // I then create a list of the holes in the polygon
                        rings.AddRange(polygon.HoleLines.Select(hole => _GetLinearRing(hole.PointList)));
                    }

                    var destinationFileName = Path.Combine("Result", "Value=" + value.ToString(CultureInfo.InvariantCulture).Replace(".", "_") + ", PolygonNumber=" + polygonNumber);

                    var attributesTable = new AttributesTable();
                    attributesTable.AddAttribute("Value", value);
                    
                    // And write it into a shape file
                    var features = new List<Feature> { new Feature(rings.Any() ? new NetTopologySuite.Geometries.Polygon(outline, rings.ToArray()) : new NetTopologySuite.Geometries.Polygon(outline), attributesTable) };
                    var writer = new ShapefileDataWriter(destinationFileName) { Header = ShapefileDataWriter.GetHeader(features[0], features.Count) };
                    writer.Write(features);

                    polygonNumber++;
                }
            }
```
I know the result should look something like this:

![howitshouldlooklike](https://user-images.githubusercontent.com/8628858/31119610-e53219dc-a874-11e7-810b-e50686eb9eac.png)

But the result looks like this

![untitled2](https://user-images.githubusercontent.com/8628858/31119726-3bacd39c-a875-11e7-8c03-af808d2d22f9.png)

I can kind of get to the right result by disabling some of the polygons like below, but I am failing to understand whats going on

![untitled3](https://user-images.githubusercontent.com/8628858/31119854-b8406040-a875-11e7-964b-6d44a80d3765.png)

So what could be going on? 

My assumptions are:
1) A contour array of 12.5, 13 will produce polygons Through TracingPolygons where all those with Outline.Value = 12.5 are for the contour going TO 12.5
2) Each polygon has an outline that defined the outline and a series of hole lines that in reverse has coordinates for the holes.
3) That I if I merge together these polygons will have a complete multipolygon for that contour ..... but according to above, I have more than that. 

I really appreciate any hints. The code you have there is not trivial.

I have attached the small test application I have with data and dependencies to nettopologysuite included if you need to debug.

Kind Regards 
[ConsoleApp11.zip](https://github.com/meteoinfo/wContour_CSharp/files/1351864/ConsoleApp11.zip)
Franz

**Comment by Yaqiang** [comment]
You can check the source code of CreateShadedLayer function in  https://github.com/meteoinfo/MeteoInfoLib_CSharp/blob/master/Data/MeteoData/DrawMeteoData.cs

**Comment by JustinCase1089** [comment]
Ok, I ended up getting all the source code trying to reproduce the issue from within the MeteoInfo application ... (it would be fantastic if you would try out the application I attached to start with though ... spent a lot of time making the issue easy digestable ;-)). But when I try to load the asc grid file below with my data, it goes into an infinite loop inside of wContour, so I can't proceed further :-/. The file loads fine when I select Contour, but not Shaded, so there must be a bug (?)

[test0.zip](https://github.com/meteoinfo/wContour_CSharp/files/1354356/test0.zip)

Cheers
Franz

**Comment by Yaqiang** [comment]
wContour and MeteoInfo C# have been updated (http://www.meteothinker.com/downloads/index.html), now it can create contour polygons from your sample data.
![shaded_test](https://user-images.githubusercontent.com/4408029/31187790-7fd6f778-a965-11e7-850e-ec07eff119fb.png)

**Comment by JustinCase1089** [comment]
Ok, I got it to work. I guess the LowValue and HighValue that wContour returns is not the low and high value and therefore need additional code outside of the library ... that's what mainly confused me
