### ISSUE TITLE
TracingStreamline produces no PolyLines

### ISSUE THREAD

**Issue by maeneak** [meteoinfo/wContour_CSharp#4]
Hello,
Im trying to use the TracingStreamline function in a c# application to generate PolyLines but the function returns no objects. Im sure this is just my data format, are you able to advise what array format is expected?
My data is top-left origin at 0.5 increments
u[y,x]
v[y,x]
x[0 to 360]
y[90 to -90]
The data is being extracted using GDAL.Net.
Much appreciated

**Comment by Yaqiang** [comment]
Please follow wContour demo program code: http://www.meteothinker.com/downloads/index.html

**Comment by maeneak** [comment]
Heads up... the demo program solution is not functional in its current state. Even when I reference the DLL it runs but exits with no error when selecting menu options. I will see if I can work around it

**Comment by maeneak** [comment]
For anyone who is interested, from what I can tell the x & y arrays need to be in ascending order. So bottom-left origin. I've now discovered MeteoInfoLib which is amazing and a much more complete solution and includes wContour. Cheers
